acme_issuer letsencrypt {
    uri        https://acme-v02.api.letsencrypt.org/directory;
    state_path /var/lib/nginx/acme/letsencrypt;
    accept_terms_of_service;
}

acme_shared_zone zone=acme_shared:1M;
