---
NGINX_USER: www-data  # Nginx service user

NGINX_DOCKER_SERVICE_NAME: nginx  # Docker Nginx service name.
NGINX_DOCKER_CONTAINER_NAME: nginx_rootless  # Nginx Docker container name.

NGINX_DOCKER_DIR_NAME: nginx_docker  # Nginx Docker directory name.
NGINX_DOCKER_PATH: /opt/{{ NGINX_DOCKER_DIR_NAME }}  # Nginx Docker installation path.
NGINX_LOG_PATH: /var/log/nginx  # Nginx logs path.
NGINX_DOCKER_CONF_PATH: '{{ NGINX_DOCKER_PATH }}/conf.d'  # Docker Nginx config path.
NGINX_SITES_AVAILABLE_PATH: /etc/nginx/sites-available  # Available sites configs path.
NGINX_SITES_ENABLED_PATH: '{{ NGINX_DOCKER_PATH }}/sites-enabled'  # Enabled sites configs path.
NGINX_SNIPPETS_PATH: '{{ NGINX_DOCKER_PATH }}/snippets'  # Config snippets path.
NGINX_DOCKER_WWW_PATH: '{{ NGINX_DOCKER_PATH }}/www'  # Docker www webcontent path.
NGINX_DOCKER_SSL_PATH: '{{ NGINX_DOCKER_PATH }}/ssl'  # Docker SSL files path.
NGINX_SSL_CERT_PATH: '{{ NGINX_DOCKER_SSL_PATH }}/{{ SSL_CERT_NAME }}'  # SSL cert path.
NGINX_SSL_KEY_PATH: '{{ NGINX_DOCKER_SSL_PATH }}/{{ SSL_KEY_NAME }}'  # SSL key path.
NGINX_SSL_DH_PATH: '{{ NGINX_DOCKER_SSL_PATH }}/{{ SSL_DH_NAME }}'  # Diffie-Hellman file path.

CERTBOT_SERVICE_NAME: certbot  # Docker Certbot service name.
CERTBOT_CONTAINER_NAME: certbot_container  # Docker Certbot container name.
CERTBOT_VOLUME_NAME: certs  # Volume name for SSL certificates.
