---
- name: Deploy WireGuard VPN
  hosts: vpn_server
  become: true

  vars_files:
    - vars.yml

  roles:
    - role: geerlingguy.docker
      tags: docker

    - role: nginx
      tags: nginx

    - role: authelia
      tags: authelia
