---
USERNAME: '{{ ansible_user }}'  # Username of your user on the target Linux machine.
DOCKER_APT_GPG_KEY_PATH: /etc/apt/keyrings/docker.asc  # Path to the Docker GPG key file for APT.
DOCKER_SERVICES_NETWORK_NAME: wg-network  # Docker Network name for related services.
