---
DOCKER_NETWORK_NAME: wg-network  # Docker Network name for related services.
WG_DOCKER_IMAGE_VERSION: latest  # WireGuard Docker image version.

WG_PORT: 51820  # The public UDP port of your VPN server.
WG_DEFAULT_ADDRESS: 10.8.0.x  # Clients IP address range.
WG_DEFAULT_DNS: 1.1.1.1, 1.0.0.1  # DNS server clients will use.

WG_LANG: en  # Web UI language
WG_UI_PASSWORD: foobar123  # Set the WebUI Password.
WG_UI_TRAFFIC_STATS: true  # Enable detailed RX / TX client stats in Web UI.
WG_UI_CHART_TYPE: 0 # Type of chart for displaying statistics; 0 Charts disabled, 1 # Line chart, 2 # Area chart, 3  # Bar chart.
