---
DOCKER_SERVICES_NETWORK_NAME: wg-network  # Docker Network name for related services.
WG_DOCKER_IMAGE_VERSION: latest  # WireGuard Docker image version.

WG_PORT: 51820  # The public UDP port of VPN server.
WG_DEFAULT_ADDRESS: 10.8.0.x  # Clients IP address range.
WG_DEFAULT_DNS: 1.1.1.1, 1.0.0.1  # DNS server clients will use.

WG_LANG: en  # WebUI language.
WG_UI_PASSWORD: foobar123  # WebUI Password.
WG_UI_TRAFFIC_STATS: true  # Enable detailed RX / TX client stats in WebUI.
WG_UI_CHART_TYPE: 0 # Type of chart for displaying statistics; 0 Charts disabled, 1 # Line chart, 2 # Area chart, 3  # Bar chart.

# WG_PRE_UP_FIREWALL_RULES: |
#   iptables -P FORWARD DROP;
#   iptables -A FORWARD -i wg0 -d 10.8.0.0/24 -j ACCEPT;
#   iptables -t nat -A POSTROUTING -o eth0 -s 10.8.0.0/24 -j MASQUERADE;
#   iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 1234 -j DNAT --to-destination 10.8.0.2:1234;

# WG_POST_UP:

# WG_PRE_DOWN_FIREWALL_RULES: |
#   iptables -D FORWARD -i wg0 -d 10.8.0.0/24 -j ACCEPT;
#   iptables -t nat -D POSTROUTING -o eth0 -s 10.8.0.0/24 -j MASQUERADE;
#   iptables -D PREROUTING -t nat -i eth0 -p tcp --dport 1234 -j DNAT --to-destination 10.8.0.2:1234;

# WG_POST_DOWN:
