---
- name: Install Pi-hole DNS server
  block:
    - name: Create Pi-hole Docker dirs
      file:
        path: '{{ directory }}'
        state: directory
        mode: 0755
      loop_control:
        loop_var: directory
      loop:
        - '{{ PIHOLE_DOCKER_PATH }}'
        - '{{ PIHOLE_CONFIG_PATH }}'
      become: true

    - name: Apply Pi-hole nginx config
      template:
        src: nginx_dns.conf.j2
        dest: '{{ NGINX_SITES_ENABLED_PATH }}/dns.conf'
        owner: root
        group: root
        mode: 0644
      become: true

    - name: Apply Pi-hole Docker Compose template
      template:
        src: docker-compose.yml.j2
        dest: '{{ PIHOLE_DOCKER_PATH }}/docker-compose.yml'
        owner: root
        group: root
        mode: 0644
      become: true

    - name: Run Docker Compose
      shell: docker compose down && docker compose up -d
      args:
        chdir: '{{ service_path }}'
      loop_control:
        loop_var: service_path
      loop:
        - '{{ PIHOLE_DOCKER_PATH }}'
        - '{{ NGINX_DOCKER_PATH }}'

    - name: Set Pi-hole admin password
      shell: docker exec -it {{ PIHOLE_DOCKER_CONTAINER_NAME }} pihole admin password {{ PIHOLE_ADMIN_PASSWORD }}
      no_log: true

  tags: dns
