---
- name: Docker
  block:
    - name: Check if Docker exists
      stat:
        path: /usr/bin/docker
      register: docker_installed

    - name: Install Docker
      block:
        - include_tasks: debian_install.yml
          when: ansible_os_family == 'Debian'

        - include_tasks: fedora_install.yml
          when: ansible_os_family == 'RedHat'

        - name: Create Docker group
          group:
            name: docker
            state: present

        - name: Add user to docker group
          user:
            name: '{{ USERNAME }}'
            groups: docker
            append: true

        - name: Restart Docker service
          service:
            name: docker
            enabled: true
            state: restarted

        # Ignore the warning about reset_connection.
        # It functions correctly in this context.
        - name: Apply user changes
          meta: reset_connection

      become: true
      when: not docker_installed.stat.exists

    - name: Create Docker network
      docker_network:
        name: '{{ DOCKER_SERVICES_NETWORK_NAME }}'
        driver: bridge
        state: present

  tags: docker
