---
- block:
    - name: Apply dnf config
      blockinfile:
        block: "{{ lookup('file', 'dnf.conf') }}"
        path: /etc/dnf/dnf.conf

    - name: Disable OpenH264 repo
      shell:
        cmd: |
          dnf config-manager --set-disabled fedora-cisco-openh264
          dnf clean all

    - name: Install python3-libdnf5
      shell: rpm -q python3-libdnf5 || dnf install -y python3-libdnf5
      changed_when: false

    - name: Uninstall garbage
      dnf:
        name:
          - nano
        state: absent
        allowerasing: true
        autoremove: true

    - name: Update Fedora system
      dnf:
        name: '*'
        state: latest
        update_cache: true
        install_weak_deps: false

    - name: Autoremove pkgs
      dnf:
        autoremove: true

    - name: Install necessary packages
      dnf:
        name:
          - bash-completion
          - curl
          - vim
        state: latest
        update_cache: true
        install_weak_deps: false

  become: true
