---
- name: Configure Debian-based system
  include_tasks: debian_tasks.yml
  when: ansible_os_family == 'Debian'

- name: Configure RedHat-based system
  include_tasks: redhat_tasks.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: auth.yml
