---
- name: Install chronyd to Fedora
  dnf:
    name: chronyd
    state: latest
    update_cache: true
    install_weak_deps: false
  when: ansible_os_family == 'RedHat'
  become: true

- name: Apply chrony config
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    mode: 0644
  notify: Restart chronyd
  become: true
